using System;
using System.Collections.Generic;

namespace ClipboardManager.Core.Services;

public record LanguageOption(string Code, string NativeName, string EnglishName);

/// <summary>
/// Centralized localization service providing multi-language support (English, Vietnamese, Chinese, Japanese, Korean, Spanish, French, German, Russian, Portuguese).
/// </summary>
public static class LocalizationService
{
    public static readonly IReadOnlyList<LanguageOption> SupportedLanguages = new List<LanguageOption>
    {
        new("en", "English", "English"),
        new("vi", "Tiếng Việt", "Vietnamese"),
        new("zh", "简体中文", "Simplified Chinese"),
        new("ja", "日本語", "Japanese"),
        new("ko", "한국어", "Korean"),
        new("es", "Español", "Spanish"),
        new("fr", "Français", "French"),
        new("de", "Deutsch", "German"),
        new("ru", "Русский", "Russian"),
        new("pt", "Português", "Portuguese")
    };

    private static string _currentLanguage = "en";

    public static event Action? LanguageChanged;

    public static string CurrentLanguage
    {
        get => _currentLanguage;
        set => SetLanguage(value);
    }

    public static void SetLanguage(string? code)
    {
        var normalized = NormalizeLanguageCode(code);
        if (_currentLanguage == normalized) return;
        _currentLanguage = normalized;
        LanguageChanged?.Invoke();
    }

    public static string NormalizeLanguageCode(string? code)
    {
        if (string.IsNullOrWhiteSpace(code)) return "en";
        var c = code.Trim().ToLowerInvariant();
        if (c.StartsWith("vi")) return "vi";
        if (c.StartsWith("zh")) return "zh";
        if (c.StartsWith("ja")) return "ja";
        if (c.StartsWith("ko")) return "ko";
        if (c.StartsWith("es")) return "es";
        if (c.StartsWith("fr")) return "fr";
        if (c.StartsWith("de")) return "de";
        if (c.StartsWith("ru")) return "ru";
        if (c.StartsWith("pt")) return "pt";
        return "en";
    }

    public static string Get(string key, params object[] args)
    {
        if (string.IsNullOrEmpty(key)) return "";

        string? value = null;
        if (Translations.TryGetValue(_currentLanguage, out var langDict))
        {
            langDict.TryGetValue(key, out value);
        }

        if (value is null && _currentLanguage != "en" && Translations.TryGetValue("en", out var enDict))
        {
            enDict.TryGetValue(key, out value);
        }

        value ??= key;

        if (args is { Length: > 0 })
        {
            try
            {
                return string.Format(value, args);
            }
            catch (FormatException)
            {
                return value;
            }
        }
        return value;
    }

    public static string T(string key, params object[] args) => Get(key, args);

    private static readonly Dictionary<string, Dictionary<string, string>> Translations = new(StringComparer.OrdinalIgnoreCase)
    {
        ["en"] = new()
        {
            // Settings Window
            ["Settings_Title"] = "Clipboard Manager — Settings",
            ["Settings_Heading"] = "Settings",
            ["Settings_Subtitle"] = "System configuration",
            ["Settings_General_Title"] = "General",
            ["Settings_General_Subtitle"] = "Keyboard shortcuts, history recording, and application interface",
            ["Settings_Privacy_Title"] = "Privacy",
            ["Settings_Privacy_Subtitle"] = "Data security, history encryption, and sensitive data protection",
            ["Settings_Retention_Title"] = "Retention",
            ["Settings_Snippets_Title"] = "Snippets",
            ["Settings_Tab_General"] = "General",
            ["Settings_Tab_Privacy"] = "Privacy",
            ["Settings_Tab_Retention"] = "Retention",
            ["Settings_Tab_Snippets"] = "Snippets",

            ["Settings_Language"] = "Language",
            ["Settings_Language_Hint"] = "Interface display language.",
            ["Settings_Hotkey"] = "Quick Paste shortcut",
            ["Settings_Hotkey_Hint"] = "Click the box and press the new shortcut, e.g. Ctrl+Shift+V or Win+Alt+V.",
            ["Settings_CaptureHistory"] = "Record clipboard history",
            ["Settings_KeepAtMost"] = "Keep at most",
            ["Settings_ItemsCountHint"] = "items (pinned items and snippets don't count)",
            ["Settings_Ocr"] = "Recognize text in copied images (Windows OCR, offline)",
            ["Settings_OcrNoLang"] = "No OCR language is installed. Add a language with OCR support in Windows Settings › Time & language › Language.",
            ["Settings_OcrRecognizes"] = "Recognizes {0}. Add more languages in Windows Settings › Time & language › Language (e.g. Vietnamese).",
            ["Settings_Transparency"] = "Enable iOS-style frosted glass transparency",
            ["Settings_Opacity"] = "Opacity",
            ["Settings_TransparencyHint"] = "Windows 11 Acrylic blur + translucent rounded widget card like modern iOS.",

            ["Settings_DetectSensitive"] = "Detect secrets (API keys, tokens, passwords) and hide them",
            ["Settings_NeverPasswords"] = "Never store passwords",
            ["Settings_NeverKeys"] = "Never store private keys",
            ["Settings_ExcludedApps"] = "Don't record copies from these apps",
            ["Settings_ExcludedHint"] = "One app per line (process name, e.g. KeePass). Matches any app whose name contains it.",
            ["Settings_Encrypt"] = "Encrypt the history with my Windows account (DPAPI)",
            ["Settings_EncryptHint"] = "Text, formatting and images are encrypted on disk; only your Windows account on this PC can read them, without a password. The search index is kept in memory. Changing this rewrites the whole history (a few seconds).",

            ["Settings_RetentionHint"] = "How long each kind of item is kept, in minutes. 0 = keep until deleted. Pinned items and snippets never expire.",
            ["Settings_Kind"] = "Kind",
            ["Settings_Minutes"] = "Minutes",


            ["Settings_SnippetsHint"] = "Reusable text for Quick Paste (type:snippet). Variables: {0}. Changes here are saved immediately.",
            ["Settings_NameCol"] = "Name",
            ["Settings_TextCol"] = "Text",
            ["Settings_NewSnippet"] = "New…",
            ["Settings_EditSnippet"] = "Edit…",
            ["Settings_DeleteSnippet"] = "Delete",
            ["Settings_Save"] = "Save",
            ["Settings_Cancel"] = "Cancel",

            // Kinds
            ["Kind_Text"] = "Text",
            ["Kind_Code"] = "Code (SQL, JSON, shell…)",
            ["Kind_Url"] = "Links",
            ["Kind_Email"] = "Email addresses",
            ["Kind_Phone"] = "Phone numbers",
            ["Kind_Number"] = "Numbers",
            ["Kind_Image"] = "Images",
            ["Kind_Files"] = "Files",
            ["Kind_Sensitive"] = "Secrets (keys, tokens)",
            ["Kind_Password"] = "Passwords",

            // Quick Paste Window
            ["QuickPaste_Title"] = "Quick Paste",
            ["QuickPaste_SearchPlaceholder"] = "Search clipboard…",
            ["QuickPaste_All"] = "All",
            ["QuickPaste_Code"] = "Code",
            ["QuickPaste_Images"] = "Images",
            ["QuickPaste_Pinned"] = "Pinned",
            ["QuickPaste_Snippets"] = "Snippets",
            ["QuickPaste_RecentSearches"] = "RECENT SEARCHES",
            ["QuickPaste_ClearRecent"] = "Clear",
            ["QuickPaste_Filters"] = "FILTERS",
            ["QuickPaste_FilterType"] = "🏷️ Type",
            ["QuickPaste_FilterPinned"] = "📌 Pinned",
            ["QuickPaste_FilterDate"] = "📅 Date",
            ["QuickPaste_FilterSensitive"] = "🔒 Sensitive",
            ["QuickPaste_PinTooltip"] = "Pin window (Ctrl+T)",
            ["QuickPaste_DockTooltip"] = "Snap widget to screen edge (Ctrl+D)",
            ["QuickPaste_SettingsTooltip"] = "Settings (Ctrl+,)",
            ["QuickPaste_HelpTooltip"] = "Keyboard shortcuts (F1)",
            ["QuickPaste_StopStack"] = "Stop Stack",
            ["QuickPaste_Next"] = "Next (Ctrl+V)",
            ["QuickPaste_ItemsCount"] = "{0} items",
            ["QuickPaste_EmptyTitle"] = "Clipboard history is empty",
            ["QuickPaste_EmptySubtitle"] = "Items you copy will appear here automatically",

            // Tray Menu
            ["Tray_QuickPaste"] = "Quick Paste",
            ["Tray_StopPasteStack"] = "Stop paste stack",
            ["Tray_PauseCapture"] = "Pause clipboard capture",
            ["Tray_ResumeCapture"] = "Resume clipboard capture",
            ["Tray_ClearHistory"] = "Clear history (keeps pinned)",
            ["Tray_StartWithWindows"] = "Start with Windows",
            ["Tray_OpenDataFolder"] = "Open data folder",
            ["Tray_Settings"] = "Settings…",
            ["Tray_EditSettingsJson"] = "Edit settings.json (advanced)",
            ["Tray_CheckForUpdates"] = "Check for updates…",
            ["Tray_Exit"] = "Exit",
            ["Tray_RunningTooltip"] = "Clipboard Manager (recording)\n{0} to open",
            ["Tray_PausedTooltip"] = "Clipboard Manager (paused)\n{0} to open",

            // Welcome & Tips
            ["Welcome_Title"] = "Advanced Clipboard Manager",
            ["Welcome_Message"] = "App is running in the background! Press {0} anywhere to open, or click this tray icon.",
            ["CloseTip_Title"] = "Advanced Clipboard Manager",
            ["CloseTip_Message"] = "Clipboard Manager is minimized to tray. Press {0} anytime to bring it back.",
            ["Header_Hotkey_Tooltip"] = "Press {0} anywhere to open Quick Paste",
            ["Footer_Items_Hint"] = "{0} items · {1} anywhere",

            // Dialogs
            ["Dialog_ClearHistoryTitle"] = "Clear history",
            ["Dialog_ClearHistoryConfirm"] = "Delete all clipboard history except pinned items?",
            ["Dialog_DeleteSnippetTitle"] = "Delete snippet",
            ["Dialog_DeleteSnippetConfirm"] = "Delete snippet \"{0}\"?",
            ["Snippet_TitleNew"] = "New snippet",
            ["Snippet_TitleEdit"] = "Edit snippet",
            ["Snippet_Name"] = "Name",
            ["Snippet_Text"] = "Text (expandable with {date}, {time}, {clip})",
            ["Snippet_Save"] = "Save",
            ["Snippet_Cancel"] = "Cancel"
        },

        ["vi"] = new()
        {
            // Settings Window
            ["Settings_Title"] = "Trình quản lý Clipboard — Cài đặt",
            ["Settings_Heading"] = "Cài đặt",
            ["Settings_Subtitle"] = "Cấu hình hệ thống",
            ["Settings_General_Title"] = "Chung",
            ["Settings_General_Subtitle"] = "Cài đặt phím tắt, ghi nhớ lịch sử và giao diện ứng dụng",
            ["Settings_Privacy_Title"] = "Quyền riêng tư",
            ["Settings_Privacy_Subtitle"] = "Bảo mật dữ liệu, mã hóa lịch sử và bỏ qua thông tin nhạy cảm",
            ["Settings_Retention_Title"] = "Thời gian lưu trữ",
            ["Settings_Snippets_Title"] = "Mẫu văn bản",
            ["Settings_Tab_General"] = "Chung",
            ["Settings_Tab_Privacy"] = "Quyền riêng tư",
            ["Settings_Tab_Retention"] = "Thời gian lưu trữ",
            ["Settings_Tab_Snippets"] = "Mẫu văn bản",

            ["Settings_Language"] = "Ngôn ngữ giao diện",
            ["Settings_Language_Hint"] = "Chọn ngôn ngữ hiển thị cho ứng dụng.",
            ["Settings_Hotkey"] = "Phím tắt Dán nhanh",
            ["Settings_Hotkey_Hint"] = "Nhấp vào ô và bấm tổ hợp phím mới, ví dụ Ctrl+Shift+V hoặc Win+Alt+V.",
            ["Settings_CaptureHistory"] = "Ghi lại lịch sử clipboard",
            ["Settings_KeepAtMost"] = "Lưu giữ tối đa",
            ["Settings_ItemsCountHint"] = "mục (không tính mục đã ghim và mẫu văn bản)",
            ["Settings_Ocr"] = "Nhận diện chữ trong ảnh sao chép (Windows OCR, offline)",
            ["Settings_OcrNoLang"] = "Chưa cài ngôn ngữ OCR. Thêm ngôn ngữ hỗ trợ OCR trong Windows Settings › Time & language › Language.",
            ["Settings_OcrRecognizes"] = "Nhận diện {0}. Cài thêm ngôn ngữ trong Windows Settings › Time & language › Language (ví dụ: Tiếng Việt).",
            ["Settings_Transparency"] = "Bật hiệu ứng trong suốt kính mờ kiểu iOS",
            ["Settings_Opacity"] = "Độ mờ đục",
            ["Settings_TransparencyHint"] = "Hiệu ứng làm mờ Acrylic Windows 11 + thẻ widget bo góc trong suốt như iOS.",

            ["Settings_DetectSensitive"] = "Phát hiện bí mật (API key, token, mật khẩu) và ẩn đi",
            ["Settings_NeverPasswords"] = "Không bao giờ lưu mật khẩu",
            ["Settings_NeverKeys"] = "Không bao giờ lưu khóa bí mật (private keys)",
            ["Settings_ExcludedApps"] = "Không ghi bản sao chép từ các ứng dụng này",
            ["Settings_ExcludedHint"] = "Mỗi dòng một ứng dụng (tên tiến trình, ví dụ: KeePass).",
            ["Settings_Encrypt"] = "Mã hóa lịch sử bằng tài khoản Windows (DPAPI)",
            ["Settings_EncryptHint"] = "Văn bản, định dạng và ảnh được mã hóa trên đĩa; chỉ tài khoản Windows của bạn trên máy này mới có thể mở.",

            ["Settings_RetentionHint"] = "Thời gian lưu trữ từng loại mục (tính theo phút). 0 = lưu cho đến khi xóa. Mục đã ghim và mẫu văn bản không bao giờ hết hạn.",
            ["Settings_Kind"] = "Loại nội dung",
            ["Settings_Minutes"] = "Số phút",


            ["Settings_SnippetsHint"] = "Đoạn văn bản mẫu dùng cho Dán nhanh (gõ: type:snippet). Biến: {0}. Thay đổi được lưu ngay lập tức.",
            ["Settings_NameCol"] = "Tên gợi nhớ",
            ["Settings_TextCol"] = "Nội dung",
            ["Settings_NewSnippet"] = "Tạo mới…",
            ["Settings_EditSnippet"] = "Sửa…",
            ["Settings_DeleteSnippet"] = "Xóa",
            ["Settings_Save"] = "Lưu thay đổi",
            ["Settings_Cancel"] = "Hủy bỏ",

            // Kinds
            ["Kind_Text"] = "Văn bản",
            ["Kind_Code"] = "Mã nguồn (SQL, JSON, shell…)",
            ["Kind_Url"] = "Liên kết mạng",
            ["Kind_Email"] = "Địa chỉ email",
            ["Kind_Phone"] = "Số điện thoại",
            ["Kind_Number"] = "Chữ số",
            ["Kind_Image"] = "Hình ảnh",
            ["Kind_Files"] = "Tệp tin",
            ["Kind_Sensitive"] = "Bí mật (khóa, token)",
            ["Kind_Password"] = "Mật khẩu",

            // Quick Paste Window
            ["QuickPaste_Title"] = "Dán nhanh",
            ["QuickPaste_SearchPlaceholder"] = "Tìm kiếm clipboard…",
            ["QuickPaste_All"] = "Tất cả",
            ["QuickPaste_Code"] = "Mã nguồn",
            ["QuickPaste_Images"] = "Hình ảnh",
            ["QuickPaste_Pinned"] = "Đã ghim",
            ["QuickPaste_Snippets"] = "Mẫu văn bản",
            ["QuickPaste_RecentSearches"] = "TÌM KIẾM GẦN ĐÂY",
            ["QuickPaste_ClearRecent"] = "Xóa lịch sử",
            ["QuickPaste_Filters"] = "BỘ LỌC TÌM KIẾM",
            ["QuickPaste_FilterType"] = "🏷️ Loại",
            ["QuickPaste_FilterPinned"] = "📌 Đã ghim",
            ["QuickPaste_FilterDate"] = "📅 Ngày",
            ["QuickPaste_FilterSensitive"] = "🔒 Nhạy cảm",
            ["QuickPaste_PinTooltip"] = "Ghim cửa sổ (Ctrl+T)",
            ["QuickPaste_DockTooltip"] = "Gắn cạnh màn hình (Ctrl+D)",
            ["QuickPaste_SettingsTooltip"] = "Cài đặt (Ctrl+,)",
            ["QuickPaste_HelpTooltip"] = "Phím tắt trợ giúp (F1)",
            ["QuickPaste_StopStack"] = "Dừng Stack",
            ["QuickPaste_Next"] = "Tiếp theo (Ctrl+V)",
            ["QuickPaste_ItemsCount"] = "{0} mục",
            ["QuickPaste_EmptyTitle"] = "Lịch sử clipboard đang trống",
            ["QuickPaste_EmptySubtitle"] = "Nội dung bạn sao chép sẽ tự động xuất hiện tại đây",

            // Tray Menu
            ["Tray_QuickPaste"] = "Dán nhanh",
            ["Tray_StopPasteStack"] = "Dừng dán ngăn xếp",
            ["Tray_PauseCapture"] = "Tạm dừng ghi clipboard",
            ["Tray_ResumeCapture"] = "Tiếp tục ghi clipboard",
            ["Tray_ClearHistory"] = "Xóa lịch sử (giữ mục đã ghim)",
            ["Tray_StartWithWindows"] = "Khởi động cùng Windows",
            ["Tray_OpenDataFolder"] = "Mở thư mục dữ liệu",
            ["Tray_Settings"] = "Cài đặt…",
            ["Tray_EditSettingsJson"] = "Sửa settings.json (nâng cao)",
            ["Tray_CheckForUpdates"] = "Kiểm tra cập nhật…",
            ["Tray_Exit"] = "Thoát ứng dụng",
            ["Tray_RunningTooltip"] = "Trình quản lý Clipboard (đang ghi)\n{0} để mở",
            ["Tray_PausedTooltip"] = "Trình quản lý Clipboard (tạm dừng)\n{0} để mở",

            // Welcome & Tips
            ["Welcome_Title"] = "Advanced Clipboard Manager",
            ["Welcome_Message"] = "Ứng dụng đang chạy nền! Bấm {0} ở bất kỳ đâu để mở, hoặc nhấp vào biểu tượng dưới khay hệ thống.",
            ["CloseTip_Title"] = "Advanced Clipboard Manager",
            ["CloseTip_Message"] = "Ứng dụng vẫn đang chạy ở khay hệ thống. Bấm {0} để mở lại bất cứ lúc nào.",
            ["Header_Hotkey_Tooltip"] = "Bấm {0} ở bất kỳ đâu để mở Quick Paste",
            ["Footer_Items_Hint"] = "{0} mục · {1} ở mọi nơi",

            // Dialogs
            ["Dialog_ClearHistoryTitle"] = "Xóa lịch sử",
            ["Dialog_ClearHistoryConfirm"] = "Xóa toàn bộ lịch sử sao chép ngoại trừ các mục đã ghim?",
            ["Dialog_DeleteSnippetTitle"] = "Xóa mẫu văn bản",
            ["Dialog_DeleteSnippetConfirm"] = "Xóa mẫu văn bản \"{0}\"?",
            ["Snippet_TitleNew"] = "Tạo mẫu văn bản mới",
            ["Snippet_TitleEdit"] = "Sửa mẫu văn bản",
            ["Snippet_Name"] = "Tên gợi nhớ",
            ["Snippet_Text"] = "Nội dung (hỗ trợ biến {date}, {time}, {clip})",
            ["Snippet_Save"] = "Lưu lại",
            ["Snippet_Cancel"] = "Hủy bỏ"
        },

        ["zh"] = new()
        {
            // Settings Window
            ["Settings_Title"] = "剪贴板管理器 — 设置",
            ["Settings_Heading"] = "设置",
            ["Settings_Subtitle"] = "系统配置",
            ["Settings_General_Title"] = "常规",
            ["Settings_General_Subtitle"] = "快捷键、历史记录限制和应用界面",
            ["Settings_Privacy_Title"] = "隐私",
            ["Settings_Privacy_Subtitle"] = "数据安全、历史记录加密与敏感数据保护",
            ["Settings_Retention_Title"] = "保留期限",
            ["Settings_Snippets_Title"] = "常用文本",
            ["Settings_Tab_General"] = "常规",
            ["Settings_Tab_Privacy"] = "隐私",
            ["Settings_Tab_Retention"] = "保留期限",
            ["Settings_Tab_Snippets"] = "常用文本",

            ["Settings_Language"] = "界面语言",
            ["Settings_Language_Hint"] = "选择应用程序的显示语言。",
            ["Settings_Hotkey"] = "快速粘贴快捷键",
            ["Settings_Hotkey_Hint"] = "点击文本框并按下新快捷键，例如 Ctrl+Shift+V 或 Win+Alt+V。",
            ["Settings_CaptureHistory"] = "记录剪贴板历史",
            ["Settings_KeepAtMost"] = "最多保留",
            ["Settings_ItemsCountHint"] = "项（固定项和常用文本不计入）",
            ["Settings_Ocr"] = "识别复制图片中的文字（Windows OCR，离线）",
            ["Settings_OcrNoLang"] = "未安装 OCR 语言包。请在 Windows 设置 › 时间和语言 › 语言 中添加。",
            ["Settings_OcrRecognizes"] = "已识别语言：{0}。可在 Windows 设置中添加更多语言。",
            ["Settings_Transparency"] = "启用 iOS 风格磨砂玻璃透明效果",
            ["Settings_Opacity"] = "不透明度",
            ["Settings_TransparencyHint"] = "Windows 11 亚克力模糊效果 + 现代 iOS 风格半透明圆角卡片。",

            ["Settings_DetectSensitive"] = "自动检测并隐藏机密信息（API 密钥、令牌、密码）",
            ["Settings_NeverPasswords"] = "从不保存密码",
            ["Settings_NeverKeys"] = "从不保存私钥",
            ["Settings_ExcludedApps"] = "不记录来自以下应用的复制内容",
            ["Settings_ExcludedHint"] = "每行一个应用名称（进程名，如 KeePass）。",
            ["Settings_Encrypt"] = "使用 Windows 账户加密历史记录（DPAPI）",
            ["Settings_EncryptHint"] = "文本、格式和图片在磁盘上均被加密；只有当前电脑上的该 Windows 账户可读取。",

            ["Settings_RetentionHint"] = "各类型内容的保留时间（分钟）。0 = 永久保留直至手动删除。固定项与常用文本永不过期。",
            ["Settings_Kind"] = "类型",
            ["Settings_Minutes"] = "分钟",


            ["Settings_SnippetsHint"] = "可重复使用的常用文本片段（输入 type:snippet）。变量：{0}。修改即时保存。",
            ["Settings_NameCol"] = "名称",
            ["Settings_TextCol"] = "内容",
            ["Settings_NewSnippet"] = "新建…",
            ["Settings_EditSnippet"] = "编辑…",
            ["Settings_DeleteSnippet"] = "删除",
            ["Settings_Save"] = "保存",
            ["Settings_Cancel"] = "取消",

            // Kinds
            ["Kind_Text"] = "纯文本",
            ["Kind_Code"] = "代码（SQL、JSON 等）",
            ["Kind_Url"] = "链接",
            ["Kind_Email"] = "电子邮件",
            ["Kind_Phone"] = "电话号码",
            ["Kind_Number"] = "数字",
            ["Kind_Image"] = "图片",
            ["Kind_Files"] = "文件",
            ["Kind_Sensitive"] = "机密数据（密钥、令牌）",
            ["Kind_Password"] = "密码",

            // Quick Paste Window
            ["QuickPaste_Title"] = "快速粘贴",
            ["QuickPaste_SearchPlaceholder"] = "搜索剪贴板…",
            ["QuickPaste_All"] = "全部",
            ["QuickPaste_Code"] = "代码",
            ["QuickPaste_Images"] = "图片",
            ["QuickPaste_Pinned"] = "已固定",
            ["QuickPaste_Snippets"] = "常用文本",
            ["QuickPaste_RecentSearches"] = "最近搜索",
            ["QuickPaste_ClearRecent"] = "清空",
            ["QuickPaste_Filters"] = "筛选条件",
            ["QuickPaste_FilterType"] = "🏷️ 类型",
            ["QuickPaste_FilterPinned"] = "📌 已固定",
            ["QuickPaste_FilterDate"] = "📅 日期",
            ["QuickPaste_FilterSensitive"] = "🔒 机密",
            ["QuickPaste_PinTooltip"] = "固定窗口 (Ctrl+T)",
            ["QuickPaste_DockTooltip"] = "贴边吸附 (Ctrl+D)",
            ["QuickPaste_SettingsTooltip"] = "设置 (Ctrl+,)",
            ["QuickPaste_HelpTooltip"] = "快捷键帮助 (F1)",
            ["QuickPaste_StopStack"] = "停止连续粘贴",
            ["QuickPaste_Next"] = "下一项 (Ctrl+V)",
            ["QuickPaste_ItemsCount"] = "{0} 项",
            ["QuickPaste_EmptyTitle"] = "剪贴板历史为空",
            ["QuickPaste_EmptySubtitle"] = "复制的内容将自动在此处显示",

            // Tray Menu
            ["Tray_QuickPaste"] = "快速粘贴",
            ["Tray_StopPasteStack"] = "停止连续粘贴",
            ["Tray_PauseCapture"] = "暂停剪贴板记录",
            ["Tray_ResumeCapture"] = "恢复剪贴板记录",
            ["Tray_ClearHistory"] = "清空历史（保留固定项）",
            ["Tray_StartWithWindows"] = "开机自启动",
            ["Tray_OpenDataFolder"] = "打开数据文件夹",
            ["Tray_Settings"] = "设置…",
            ["Tray_EditSettingsJson"] = "编辑 settings.json（高级）",
            ["Tray_CheckForUpdates"] = "检查更新…",
            ["Tray_Exit"] = "退出",
            ["Tray_RunningTooltip"] = "剪贴板管理器（记录中）\n按 {0} 打开",
            ["Tray_PausedTooltip"] = "剪贴板管理器（已暂停）\n按 {0} 打开",

            // Dialogs
            ["Dialog_ClearHistoryTitle"] = "清空历史",
            ["Dialog_ClearHistoryConfirm"] = "确定清空除固定项外的所有剪贴板记录吗？",
            ["Dialog_DeleteSnippetTitle"] = "删除常用文本",
            ["Dialog_DeleteSnippetConfirm"] = "确定删除常用文本 \"{0}\" 吗？",
            ["Snippet_TitleNew"] = "新建常用文本",
            ["Snippet_TitleEdit"] = "编辑常用文本",
            ["Snippet_Name"] = "名称",
            ["Snippet_Text"] = "内容（支持 {date}、{time}、{clip} 等变量）",
            ["Snippet_Save"] = "保存",
            ["Snippet_Cancel"] = "取消"
        },

        ["ja"] = new()
        {
            ["Settings_Title"] = "クリップボードマネージャー — 設定",
            ["Settings_Heading"] = "設定",
            ["Settings_Subtitle"] = "システム設定",
            ["Settings_General_Title"] = "一般",
            ["Settings_General_Subtitle"] = "ショートカット、履歴保持、アプリ外観の設定",
            ["Settings_Privacy_Title"] = "プライバシー",
            ["Settings_Privacy_Subtitle"] = "データセキュリティ、暗号化、機密情報の保護",
            ["Settings_Retention_Title"] = "保持期間",
            ["Settings_Snippets_Title"] = "スニペット",
            ["Settings_Tab_General"] = "一般",
            ["Settings_Tab_Privacy"] = "プライバシー",
            ["Settings_Tab_Retention"] = "保持期間",
            ["Settings_Tab_Snippets"] = "スニペット",

            ["Settings_Language"] = "言語",
            ["Settings_Language_Hint"] = "アプリの表示言語を選択します。",
            ["Settings_Hotkey"] = "クイックペーストのショートカット",
            ["Settings_Hotkey_Hint"] = "枠内をクリックして新しいショートカット（例: Ctrl+Shift+V）を押してください。",
            ["Settings_CaptureHistory"] = "クリップボード履歴を記録する",
            ["Settings_KeepAtMost"] = "最大保持件数",
            ["Settings_ItemsCountHint"] = "件（ピン留めとスニペットは除外）",
            ["Settings_Ocr"] = "画像のテキストを認識する (Windows OCR、オフライン)",
            ["Settings_OcrNoLang"] = "OCR言語がインストールされていません。",
            ["Settings_OcrRecognizes"] = "{0} を認識できます。",
            ["Settings_Transparency"] = "iOSスタイルのすりガラス透明効果を有効化",
            ["Settings_Opacity"] = "不透明度",
            ["Settings_TransparencyHint"] = "Windows 11 アクリルぼかし効果 + iOS風半透明カード。",

            ["Settings_DetectSensitive"] = "機密情報（APIキー、トークン、パスワード）を検知して非表示にする",
            ["Settings_NeverPasswords"] = "パスワードを保存しない",
            ["Settings_NeverKeys"] = "秘密鍵を保存しない",
            ["Settings_ExcludedApps"] = "次のアプリからのコピーを記録しない",
            ["Settings_ExcludedHint"] = "1行に1アプリ（プロセス名、例: KeePass）。",
            ["Settings_Encrypt"] = "Windowsアカウントで履歴を暗号化 (DPAPI)",
            ["Settings_EncryptHint"] = "テキスト・書式・画像はディスク上で暗号化されます。",

            ["Settings_RetentionHint"] = "各種類の保持期間（分）。0 = 手動削除まで保持。",
            ["Settings_Kind"] = "種類",
            ["Settings_Minutes"] = "分",


            ["Settings_SnippetsHint"] = "定型文スニペット (type:snippet)。変数: {0}。",
            ["Settings_NameCol"] = "名前",
            ["Settings_TextCol"] = "テキスト",
            ["Settings_NewSnippet"] = "新規作成…",
            ["Settings_EditSnippet"] = "編集…",
            ["Settings_DeleteSnippet"] = "削除",
            ["Settings_Save"] = "保存",
            ["Settings_Cancel"] = "キャンセル",

            ["Kind_Text"] = "テキスト",
            ["Kind_Code"] = "コード (SQL, JSONなど)",
            ["Kind_Url"] = "リンク",
            ["Kind_Email"] = "メールアドレス",
            ["Kind_Phone"] = "電話番号",
            ["Kind_Number"] = "数値",
            ["Kind_Image"] = "画像",
            ["Kind_Files"] = "ファイル",
            ["Kind_Sensitive"] = "機密情報 (キー・トークン)",
            ["Kind_Password"] = "パスワード",

            ["QuickPaste_Title"] = "クイックペースト",
            ["QuickPaste_SearchPlaceholder"] = "履歴を検索…",
            ["QuickPaste_All"] = "すべて",
            ["QuickPaste_Code"] = "コード",
            ["QuickPaste_Images"] = "画像",
            ["QuickPaste_Pinned"] = "ピン留め",
            ["QuickPaste_Snippets"] = "スニペット",
            ["QuickPaste_RecentSearches"] = "最近の検索",
            ["QuickPaste_ClearRecent"] = "クリア",
            ["QuickPaste_Filters"] = "フィルター",
            ["QuickPaste_FilterType"] = "🏷️ 種類",
            ["QuickPaste_FilterPinned"] = "📌 ピン留め",
            ["QuickPaste_FilterDate"] = "📅 日付",
            ["QuickPaste_FilterSensitive"] = "🔒 機密",
            ["QuickPaste_PinTooltip"] = "ウィンドウを固定 (Ctrl+T)",
            ["QuickPaste_DockTooltip"] = "画面端にドッキング (Ctrl+D)",
            ["QuickPaste_SettingsTooltip"] = "設定 (Ctrl+,)",
            ["QuickPaste_HelpTooltip"] = "ショートカット一覧 (F1)",
            ["QuickPaste_StopStack"] = "スタック停止",
            ["QuickPaste_Next"] = "次へ (Ctrl+V)",
            ["QuickPaste_ItemsCount"] = "{0} 件",
            ["QuickPaste_EmptyTitle"] = "履歴がありません",
            ["QuickPaste_EmptySubtitle"] = "コピーした内容がここに表示されます",

            ["Tray_QuickPaste"] = "クイックペースト",
            ["Tray_StopPasteStack"] = "ペーストスタックを停止",
            ["Tray_PauseCapture"] = "記録を一時停止",
            ["Tray_ResumeCapture"] = "記録を再開",
            ["Tray_ClearHistory"] = "履歴をクリア (ピン留めを除く)",
            ["Tray_StartWithWindows"] = "Windows起動時に実行",
            ["Tray_OpenDataFolder"] = "データフォルダーを開く",
            ["Tray_Settings"] = "設定…",
            ["Tray_EditSettingsJson"] = "settings.json を編集 (詳細設定)",
            ["Tray_CheckForUpdates"] = "更新を確認…",
            ["Tray_Exit"] = "終了",
            ["Tray_RunningTooltip"] = "クリップボードマネージャー（記録中）\n{0} で開く",
            ["Tray_PausedTooltip"] = "クリップボードマネージャー（一時停止中）\n{0} で開く",

            ["Dialog_ClearHistoryTitle"] = "履歴のクリア",
            ["Dialog_ClearHistoryConfirm"] = "ピン留めを除くすべての履歴を削除しますか？",
            ["Dialog_DeleteSnippetTitle"] = "スニペットの削除",
            ["Dialog_DeleteSnippetConfirm"] = "スニペット \"{0}\" を削除しますか？",
            ["Snippet_TitleNew"] = "新しいスニペット",
            ["Snippet_TitleEdit"] = "スニペットの編集",
            ["Snippet_Name"] = "名前",
            ["Snippet_Text"] = "内容 ({date}, {time}, {clip} などの変数が利用可能)",
            ["Snippet_Save"] = "保存",
            ["Snippet_Cancel"] = "キャンセル"
        },

        ["ko"] = new()
        {
            ["Settings_Title"] = "클립보드 관리자 — 설정",
            ["Settings_Heading"] = "설정",
            ["Settings_Subtitle"] = "시스템 구성",
            ["Settings_General_Title"] = "일반",
            ["Settings_General_Subtitle"] = "단축키, 기록 보관 및 앱 인터페이스 설정",
            ["Settings_Privacy_Title"] = "개인정보 보호",
            ["Settings_Privacy_Subtitle"] = "데이터 보안, 기록 암호화 및 민감한 정보 보호",
            ["Settings_Retention_Title"] = "보관 기간",
            ["Settings_Snippets_Title"] = "스니펫",
            ["Settings_Tab_General"] = "일반",
            ["Settings_Tab_Privacy"] = "개인정보 보호",
            ["Settings_Tab_Retention"] = "보관 기간",
            ["Settings_Tab_Snippets"] = "스니펫",

            ["Settings_Language"] = "언어",
            ["Settings_Language_Hint"] = "표시할 언어를 선택합니다.",
            ["Settings_Hotkey"] = "빠른 붙여넣기 단축키",
            ["Settings_Hotkey_Hint"] = "상자를 클릭하고 새 단축키를 누르세요 (예: Ctrl+Shift+V).",
            ["Settings_CaptureHistory"] = "클립보드 기록 저장",
            ["Settings_KeepAtMost"] = "최대 보관 항목 수",
            ["Settings_ItemsCountHint"] = "개 (고정된 항목 및 스니펫 제외)",
            ["Settings_Ocr"] = "복사된 이미지의 텍스트 인식 (Windows OCR, 오프라인)",
            ["Settings_OcrNoLang"] = "OCR 언어가 설치되어 있지 않습니다.",
            ["Settings_OcrRecognizes"] = "{0} 언어를 인식합니다.",
            ["Settings_Transparency"] = "iOS 스타일 불투명 유리 효과 활성화",
            ["Settings_Opacity"] = "불투명도",
            ["Settings_TransparencyHint"] = "Windows 11 아크릴 블러 + 반투명 라운드 카드.",

            ["Settings_DetectSensitive"] = "보안 정보(API 키, 토큰, 비밀번호) 감지 및 숨김",
            ["Settings_NeverPasswords"] = "비밀번호 저장 안 함",
            ["Settings_NeverKeys"] = "개인 키 저장 안 함",
            ["Settings_ExcludedApps"] = "다음 앱의 복사 내용 기록 안 함",
            ["Settings_ExcludedHint"] = "한 줄에 하나의 앱 (프로세스 이름).",
            ["Settings_Encrypt"] = "Windows 계정으로 기록 암호화 (DPAPI)",
            ["Settings_EncryptHint"] = "텍스트, 서식 및 이미지가 디스크에 암호화되어 저장됩니다.",

            ["Settings_RetentionHint"] = "항목 유형별 보관 시간(분). 0 = 영구 보관.",
            ["Settings_Kind"] = "종류",
            ["Settings_Minutes"] = "분",


            ["Settings_SnippetsHint"] = "자주 쓰는 문구 스니펫 (type:snippet). 변수: {0}.",
            ["Settings_NameCol"] = "이름",
            ["Settings_TextCol"] = "내용",
            ["Settings_NewSnippet"] = "새로 만들기…",
            ["Settings_EditSnippet"] = "수정…",
            ["Settings_DeleteSnippet"] = "삭제",
            ["Settings_Save"] = "저장",
            ["Settings_Cancel"] = "취소",

            ["Kind_Text"] = "텍스트",
            ["Kind_Code"] = "코드 (SQL, JSON 등)",
            ["Kind_Url"] = "링크",
            ["Kind_Email"] = "이메일",
            ["Kind_Phone"] = "전화번호",
            ["Kind_Number"] = "숫자",
            ["Kind_Image"] = "이미지",
            ["Kind_Files"] = "파일",
            ["Kind_Sensitive"] = "보안 정보",
            ["Kind_Password"] = "비밀번호",

            ["QuickPaste_Title"] = "빠른 붙여넣기",
            ["QuickPaste_SearchPlaceholder"] = "클립보드 검색…",
            ["QuickPaste_All"] = "전체",
            ["QuickPaste_Code"] = "코드",
            ["QuickPaste_Images"] = "이미지",
            ["QuickPaste_Pinned"] = "고정됨",
            ["QuickPaste_Snippets"] = "스니펫",
            ["QuickPaste_RecentSearches"] = "최근 검색",
            ["QuickPaste_ClearRecent"] = "지우기",
            ["QuickPaste_Filters"] = "필터",
            ["QuickPaste_FilterType"] = "🏷️ 종류",
            ["QuickPaste_FilterPinned"] = "📌 고정됨",
            ["QuickPaste_FilterDate"] = "📅 날짜",
            ["QuickPaste_FilterSensitive"] = "🔒 보안",
            ["QuickPaste_PinTooltip"] = "창 고정 (Ctrl+T)",
            ["QuickPaste_DockTooltip"] = "화면 가장자리에 도킹 (Ctrl+D)",
            ["QuickPaste_SettingsTooltip"] = "설정 (Ctrl+,)",
            ["QuickPaste_HelpTooltip"] = "단축키 도움말 (F1)",
            ["QuickPaste_StopStack"] = "스택 중지",
            ["QuickPaste_Next"] = "다음 (Ctrl+V)",
            ["QuickPaste_ItemsCount"] = "{0}개 항목",
            ["QuickPaste_EmptyTitle"] = "클립보드 기록이 비어 있습니다",
            ["QuickPaste_EmptySubtitle"] = "복사한 내용이 여기에 자동으로 표시됩니다",

            ["Tray_QuickPaste"] = "빠른 붙여넣기",
            ["Tray_StopPasteStack"] = "붙여넣기 스택 중지",
            ["Tray_PauseCapture"] = "클립보드 기록 일시 중지",
            ["Tray_ResumeCapture"] = "클립보드 기록 다시 시작",
            ["Tray_ClearHistory"] = "기록 지우기 (고정 항목 제외)",
            ["Tray_StartWithWindows"] = "Windows 시작 시 실행",
            ["Tray_OpenDataFolder"] = "데이터 폴더 열기",
            ["Tray_Settings"] = "설정…",
            ["Tray_EditSettingsJson"] = "settings.json 편집 (고급)",
            ["Tray_CheckForUpdates"] = "업데이트 확인…",
            ["Tray_Exit"] = "종료",
            ["Tray_RunningTooltip"] = "클립보드 관리자 (기록 중)\n{0} 눌러서 열기",
            ["Tray_PausedTooltip"] = "클립보드 관리자 (일시 중지됨)\n{0} 눌러서 열기",

            ["Dialog_ClearHistoryTitle"] = "기록 지우기",
            ["Dialog_ClearHistoryConfirm"] = "고정된 항목을 제외한 모든 기록을 삭제하시겠습니까?",
            ["Dialog_DeleteSnippetTitle"] = "스니펫 삭제",
            ["Dialog_DeleteSnippetConfirm"] = "\"{0}\" 스니펫을 삭제하시겠습니까?",
            ["Snippet_TitleNew"] = "새 스니펫",
            ["Snippet_TitleEdit"] = "스니펫 편집",
            ["Snippet_Name"] = "이름",
            ["Snippet_Text"] = "내용 ({date}, {time}, {clip} 등 지원)",
            ["Snippet_Save"] = "저장",
            ["Snippet_Cancel"] = "취소"
        },

        ["es"] = new()
        {
            ["Settings_Title"] = "Administrador de Portapapeles — Configuración",
            ["Settings_Heading"] = "Configuración",
            ["Settings_Subtitle"] = "Configuración del sistema",
            ["Settings_General_Title"] = "General",
            ["Settings_General_Subtitle"] = "Atajos de teclado, límite de historial e interfaz",
            ["Settings_Privacy_Title"] = "Privacidad",
            ["Settings_Privacy_Subtitle"] = "Seguridad de datos, cifrado y protección de datos confidenciales",
            ["Settings_Retention_Title"] = "Retención",
            ["Settings_Snippets_Title"] = "Fragmentos",
            ["Settings_Tab_General"] = "General",
            ["Settings_Tab_Privacy"] = "Privacidad",
            ["Settings_Tab_Retention"] = "Retención",
            ["Settings_Tab_Snippets"] = "Fragmentos",

            ["Settings_Language"] = "Idioma",
            ["Settings_Language_Hint"] = "Idioma de la interfaz de la aplicación.",
            ["Settings_Hotkey"] = "Atajo de Pegado Rápido",
            ["Settings_Hotkey_Hint"] = "Haz clic en el recuadro y presiona el atajo (ej. Ctrl+Shift+V).",
            ["Settings_CaptureHistory"] = "Registrar historial del portapapeles",
            ["Settings_KeepAtMost"] = "Conservar como máximo",
            ["Settings_ItemsCountHint"] = "elementos (elementos fijados y fragmentos no cuentan)",
            ["Settings_Ocr"] = "Reconocer texto en imágenes (Windows OCR, sin conexión)",
            ["Settings_OcrNoLang"] = "No hay idioma OCR instalado.",
            ["Settings_OcrRecognizes"] = "Reconoce {0}.",
            ["Settings_Transparency"] = "Activar transparencia estilo cristal iOS",
            ["Settings_Opacity"] = "Opacidad",
            ["Settings_TransparencyHint"] = "Efecto acrílico de Windows 11 + tarjeta redondeada translúcida estilo iOS.",

            ["Settings_DetectSensitive"] = "Detectar y ocultar datos confidenciales (claves API, tokens, contraseñas)",
            ["Settings_NeverPasswords"] = "Nunca guardar contraseñas",
            ["Settings_NeverKeys"] = "Nunca guardar claves privadas",
            ["Settings_ExcludedApps"] = "No registrar copias de estas aplicaciones",
            ["Settings_ExcludedHint"] = "Una app por línea (nombre del proceso, ej. KeePass).",
            ["Settings_Encrypt"] = "Cifrar historial con mi cuenta de Windows (DPAPI)",
            ["Settings_EncryptHint"] = "El texto, formato e imágenes se cifran en disco.",

            ["Settings_RetentionHint"] = "Tiempo de retención en minutos. 0 = hasta que se elimine.",
            ["Settings_Kind"] = "Tipo",
            ["Settings_Minutes"] = "Minutos",


            ["Settings_SnippetsHint"] = "Texto reutilizable para Pegado Rápido (type:snippet). Variables: {0}.",
            ["Settings_NameCol"] = "Nombre",
            ["Settings_TextCol"] = "Texto",
            ["Settings_NewSnippet"] = "Nuevo…",
            ["Settings_EditSnippet"] = "Editar…",
            ["Settings_DeleteSnippet"] = "Eliminar",
            ["Settings_Save"] = "Guardar",
            ["Settings_Cancel"] = "Cancelar",

            ["Kind_Text"] = "Texto",
            ["Kind_Code"] = "Código",
            ["Kind_Url"] = "Enlaces",
            ["Kind_Email"] = "Correos electrónicos",
            ["Kind_Phone"] = "Teléfonos",
            ["Kind_Number"] = "Números",
            ["Kind_Image"] = "Imágenes",
            ["Kind_Files"] = "Archivos",
            ["Kind_Sensitive"] = "Confidencial",
            ["Kind_Password"] = "Contraseñas",

            ["QuickPaste_Title"] = "Pegado Rápido",
            ["QuickPaste_SearchPlaceholder"] = "Buscar en portapapeles…",
            ["QuickPaste_All"] = "Todo",
            ["QuickPaste_Code"] = "Código",
            ["QuickPaste_Images"] = "Imágenes",
            ["QuickPaste_Pinned"] = "Fijados",
            ["QuickPaste_Snippets"] = "Fragmentos",
            ["QuickPaste_RecentSearches"] = "BÚSQUEDAS RECIENTES",
            ["QuickPaste_ClearRecent"] = "Borrar",
            ["QuickPaste_Filters"] = "FILTROS",
            ["QuickPaste_FilterType"] = "🏷️ Tipo",
            ["QuickPaste_FilterPinned"] = "📌 Fijado",
            ["QuickPaste_FilterDate"] = "📅 Fecha",
            ["QuickPaste_FilterSensitive"] = "🔒 Confidencial",
            ["QuickPaste_PinTooltip"] = "Fijar ventana (Ctrl+T)",
            ["QuickPaste_DockTooltip"] = "Acoplar al borde (Ctrl+D)",
            ["QuickPaste_SettingsTooltip"] = "Configuración (Ctrl+,)",
            ["QuickPaste_HelpTooltip"] = "Atajos de teclado (F1)",
            ["QuickPaste_StopStack"] = "Detener pila",
            ["QuickPaste_Next"] = "Siguiente (Ctrl+V)",
            ["QuickPaste_ItemsCount"] = "{0} elementos",
            ["QuickPaste_EmptyTitle"] = "El historial está vacío",
            ["QuickPaste_EmptySubtitle"] = "Lo que copies aparecerá aquí automáticamente",

            ["Tray_QuickPaste"] = "Pegado Rápido",
            ["Tray_StopPasteStack"] = "Detener pila de pegado",
            ["Tray_PauseCapture"] = "Pausar captura",
            ["Tray_ResumeCapture"] = "Reanudar captura",
            ["Tray_ClearHistory"] = "Borrar historial (mantiene fijados)",
            ["Tray_StartWithWindows"] = "Iniciar con Windows",
            ["Tray_OpenDataFolder"] = "Abrir carpeta de datos",
            ["Tray_Settings"] = "Configuración…",
            ["Tray_EditSettingsJson"] = "Editar settings.json (avanzado)",
            ["Tray_CheckForUpdates"] = "Buscar actualizaciones…",
            ["Tray_Exit"] = "Salir",
            ["Tray_RunningTooltip"] = "Administrador de Portapapeles (grabando)\n{0} para abrir",
            ["Tray_PausedTooltip"] = "Administrador de Portapapeles (en pausa)\n{0} para abrir",

            ["Dialog_ClearHistoryTitle"] = "Borrar historial",
            ["Dialog_ClearHistoryConfirm"] = "¿Eliminar todo el historial excepto los fijados?",
            ["Dialog_DeleteSnippetTitle"] = "Eliminar fragmento",
            ["Dialog_DeleteSnippetConfirm"] = "¿Eliminar el fragmento \"{0}\"?",
            ["Snippet_TitleNew"] = "Nuevo fragmento",
            ["Snippet_TitleEdit"] = "Editar fragmento",
            ["Snippet_Name"] = "Nombre",
            ["Snippet_Text"] = "Texto (admite {date}, {time}, {clip})",
            ["Snippet_Save"] = "Guardar",
            ["Snippet_Cancel"] = "Cancelar"
        },

        ["fr"] = new()
        {
            ["Settings_Title"] = "Gestionnaire de Presse-papiers — Paramètres",
            ["Settings_Heading"] = "Paramètres",
            ["Settings_Subtitle"] = "Configuration du système",
            ["Settings_General_Title"] = "Général",
            ["Settings_General_Subtitle"] = "Raccourcis clavier, historique et interface de l'application",
            ["Settings_Privacy_Title"] = "Confidentialité",
            ["Settings_Privacy_Subtitle"] = "Sécurité des données, chiffrement et protection des données sensibles",
            ["Settings_Retention_Title"] = "Rétention",
            ["Settings_Snippets_Title"] = "Extraits",
            ["Settings_Tab_General"] = "Général",
            ["Settings_Tab_Privacy"] = "Confidentialité",
            ["Settings_Tab_Retention"] = "Rétention",
            ["Settings_Tab_Snippets"] = "Extraits",

            ["Settings_Language"] = "Langue",
            ["Settings_Language_Hint"] = "Langue d'affichage de l'application.",
            ["Settings_Hotkey"] = "Raccourci Collage Rapide",
            ["Settings_Hotkey_Hint"] = "Cliquez sur la zone et appuyez sur le raccourci (ex. Ctrl+Shift+V).",
            ["Settings_CaptureHistory"] = "Enregistrer l'historique du presse-papiers",
            ["Settings_KeepAtMost"] = "Conserver au maximum",
            ["Settings_ItemsCountHint"] = "éléments (les éléments épinglés et extraits ne comptent pas)",
            ["Settings_Ocr"] = "Reconnaître le texte dans les images (Windows OCR, hors ligne)",
            ["Settings_OcrNoLang"] = "Aucune langue OCR installée.",
            ["Settings_OcrRecognizes"] = "Reconnaît {0}.",
            ["Settings_Transparency"] = "Activer la translucidité style iOS",
            ["Settings_Opacity"] = "Opacité",
            ["Settings_TransparencyHint"] = "Flou acrylique Windows 11 + carte translucide moderne style iOS.",

            ["Settings_DetectSensitive"] = "Détecter et masquer les secrets (clés API, jetons, mots de passe)",
            ["Settings_NeverPasswords"] = "Ne jamais enregistrer les mots de passe",
            ["Settings_NeverKeys"] = "Ne jamais enregistrer les clés privées",
            ["Settings_ExcludedApps"] = "Ne pas enregistrer les copies de ces applications",
            ["Settings_ExcludedHint"] = "Une application par ligne (nom du processus).",
            ["Settings_Encrypt"] = "Chiffrer l'historique avec mon compte Windows (DPAPI)",
            ["Settings_EncryptHint"] = "Le texte et les images sont chiffrés sur le disque.",

            ["Settings_RetentionHint"] = "Durée de conservation en minutes. 0 = jusqu'à suppression.",
            ["Settings_Kind"] = "Type",
            ["Settings_Minutes"] = "Minutes",


            ["Settings_SnippetsHint"] = "Extraits de texte réutilisables (type:snippet). Variables : {0}.",
            ["Settings_NameCol"] = "Nom",
            ["Settings_TextCol"] = "Texte",
            ["Settings_NewSnippet"] = "Nouveau…",
            ["Settings_EditSnippet"] = "Modifier…",
            ["Settings_DeleteSnippet"] = "Supprimer",
            ["Settings_Save"] = "Enregistrer",
            ["Settings_Cancel"] = "Annuler",

            ["Kind_Text"] = "Texte",
            ["Kind_Code"] = "Code",
            ["Kind_Url"] = "Liens",
            ["Kind_Email"] = "E-mails",
            ["Kind_Phone"] = "Numéros de téléphone",
            ["Kind_Number"] = "Nombres",
            ["Kind_Image"] = "Images",
            ["Kind_Files"] = "Fichiers",
            ["Kind_Sensitive"] = "Secrets",
            ["Kind_Password"] = "Mots de passe",

            ["QuickPaste_Title"] = "Collage Rapide",
            ["QuickPaste_SearchPlaceholder"] = "Rechercher dans le presse-papiers…",
            ["QuickPaste_All"] = "Tout",
            ["QuickPaste_Code"] = "Code",
            ["QuickPaste_Images"] = "Images",
            ["QuickPaste_Pinned"] = "Épinglés",
            ["QuickPaste_Snippets"] = "Extraits",
            ["QuickPaste_RecentSearches"] = "RECHERCHES RÉCENTES",
            ["QuickPaste_ClearRecent"] = "Effacer",
            ["QuickPaste_Filters"] = "FILTRES",
            ["QuickPaste_FilterType"] = "🏷️ Type",
            ["QuickPaste_FilterPinned"] = "📌 Épinglé",
            ["QuickPaste_FilterDate"] = "📅 Date",
            ["QuickPaste_FilterSensitive"] = "🔒 Secret",
            ["QuickPaste_PinTooltip"] = "Épingler la fenêtre (Ctrl+T)",
            ["QuickPaste_DockTooltip"] = "Ancrer au bord de l'écran (Ctrl+D)",
            ["QuickPaste_SettingsTooltip"] = "Paramètres (Ctrl+,)",
            ["QuickPaste_HelpTooltip"] = "Raccourcis clavier (F1)",
            ["QuickPaste_StopStack"] = "Arrêter la pile",
            ["QuickPaste_Next"] = "Suivant (Ctrl+V)",
            ["QuickPaste_ItemsCount"] = "{0} éléments",
            ["QuickPaste_EmptyTitle"] = "Historique vide",
            ["QuickPaste_EmptySubtitle"] = "Les éléments copiés apparaîtront ici",

            ["Tray_QuickPaste"] = "Collage Rapide",
            ["Tray_StopPasteStack"] = "Arrêter la pile",
            ["Tray_PauseCapture"] = "Mettre en pause la capture",
            ["Tray_ResumeCapture"] = "Reprendre la capture",
            ["Tray_ClearHistory"] = "Effacer l'historique (garde les épinglés)",
            ["Tray_StartWithWindows"] = "Démarrer avec Windows",
            ["Tray_OpenDataFolder"] = "Ouvrir le dossier des données",
            ["Tray_Settings"] = "Paramètres…",
            ["Tray_EditSettingsJson"] = "Modifier settings.json (avancé)",
            ["Tray_CheckForUpdates"] = "Rechercher des mises à jour…",
            ["Tray_Exit"] = "Quitter",
            ["Tray_RunningTooltip"] = "Gestionnaire de Presse-papiers (actif)\n{0} pour ouvrir",
            ["Tray_PausedTooltip"] = "Gestionnaire de Presse-papiers (en pause)\n{0} pour ouvrir",

            ["Dialog_ClearHistoryTitle"] = "Effacer l'historique",
            ["Dialog_ClearHistoryConfirm"] = "Supprimer tout l'historique sauf les éléments épinglés ?",
            ["Dialog_DeleteSnippetTitle"] = "Supprimer l'extrait",
            ["Dialog_DeleteSnippetConfirm"] = "Supprimer l'extrait \"{0}\" ?",
            ["Snippet_TitleNew"] = "Nouvel extrait",
            ["Snippet_TitleEdit"] = "Modifier l'extrait",
            ["Snippet_Name"] = "Nom",
            ["Snippet_Text"] = "Texte (prend en charge {date}, {time}, {clip})",
            ["Snippet_Save"] = "Enregistrer",
            ["Snippet_Cancel"] = "Annuler"
        },

        ["de"] = new()
        {
            ["Settings_Title"] = "Zwischenablage-Manager — Einstellungen",
            ["Settings_Heading"] = "Einstellungen",
            ["Settings_Subtitle"] = "Systemkonfiguration",
            ["Settings_General_Title"] = "Allgemein",
            ["Settings_General_Subtitle"] = "Tastenkombinationen, Verlauf und Benutzeroberfläche",
            ["Settings_Privacy_Title"] = "Datenschutz",
            ["Settings_Privacy_Subtitle"] = "Datensicherheit, Verschlüsselung und Schutz vertraulicher Daten",
            ["Settings_Retention_Title"] = "Aufbewahrung",
            ["Settings_Snippets_Title"] = "Textbausteine",
            ["Settings_Tab_General"] = "Allgemein",
            ["Settings_Tab_Privacy"] = "Datenschutz",
            ["Settings_Tab_Retention"] = "Aufbewahrung",
            ["Settings_Tab_Snippets"] = "Textbausteine",

            ["Settings_Language"] = "Sprache",
            ["Settings_Language_Hint"] = "Anzeigesprache der Anwendung.",
            ["Settings_Hotkey"] = "Schnell-Einfügen Tastenkombination",
            ["Settings_Hotkey_Hint"] = "Klicken und Tastenkombination drücken (z.B. Strg+Umschalt+V).",
            ["Settings_CaptureHistory"] = "Zwischenablage-Verlauf aufzeichnen",
            ["Settings_KeepAtMost"] = "Maximal behalten",
            ["Settings_ItemsCountHint"] = "Einträge (Angeheftete und Bausteine zählen nicht)",
            ["Settings_Ocr"] = "Text in Bildern erkennen (Windows OCR, offline)",
            ["Settings_OcrNoLang"] = "Keine OCR-Sprache installiert.",
            ["Settings_OcrRecognizes"] = "Erkennt {0}.",
            ["Settings_Transparency"] = "Transparenz im iOS-Milchglasstil aktivieren",
            ["Settings_Opacity"] = "Deckkraft",
            ["Settings_TransparencyHint"] = "Windows 11 Acryl-Effekt + transluzente iOS-Karte.",

            ["Settings_DetectSensitive"] = "Geheimnisse erkennen (API-Schlüssel, Passwörter) und ausblenden",
            ["Settings_NeverPasswords"] = "Passwörter nie speichern",
            ["Settings_NeverKeys"] = "Private Schlüssel nie speichern",
            ["Settings_ExcludedApps"] = "Kopien dieser Apps ignorieren",
            ["Settings_ExcludedHint"] = "Eine App pro Zeile (Prozessname).",
            ["Settings_Encrypt"] = "Verlauf mit Windows-Konto verschlüsseln (DPAPI)",
            ["Settings_EncryptHint"] = "Texte und Bilder werden auf der Festplatte verschlüsselt.",

            ["Settings_RetentionHint"] = "Aufbewahrungszeit in Minuten. 0 = bis manuell gelöscht.",
            ["Settings_Kind"] = "Art",
            ["Settings_Minutes"] = "Minuten",


            ["Settings_SnippetsHint"] = "Wiederverwendbare Textbausteine (type:snippet). Variablen: {0}.",
            ["Settings_NameCol"] = "Name",
            ["Settings_TextCol"] = "Text",
            ["Settings_NewSnippet"] = "Neu…",
            ["Settings_EditSnippet"] = "Bearbeiten…",
            ["Settings_DeleteSnippet"] = "Löschen",
            ["Settings_Save"] = "Speichern",
            ["Settings_Cancel"] = "Abbrechen",

            ["Kind_Text"] = "Text",
            ["Kind_Code"] = "Code",
            ["Kind_Url"] = "Links",
            ["Kind_Email"] = "E-Mail-Adressen",
            ["Kind_Phone"] = "Telefonnummern",
            ["Kind_Number"] = "Zahlen",
            ["Kind_Image"] = "Bilder",
            ["Kind_Files"] = "Dateien",
            ["Kind_Sensitive"] = "Geheimnisse",
            ["Kind_Password"] = "Passwörter",

            ["QuickPaste_Title"] = "Schnell-Einfügen",
            ["QuickPaste_SearchPlaceholder"] = "Zwischenablage durchsuchen…",
            ["QuickPaste_All"] = "Alle",
            ["QuickPaste_Code"] = "Code",
            ["QuickPaste_Images"] = "Bilder",
            ["QuickPaste_Pinned"] = "Angeheftet",
            ["QuickPaste_Snippets"] = "Bausteine",
            ["QuickPaste_RecentSearches"] = "LETZTE SUCHEN",
            ["QuickPaste_ClearRecent"] = "Löschen",
            ["QuickPaste_Filters"] = "FILTER",
            ["QuickPaste_FilterType"] = "🏷️ Typ",
            ["QuickPaste_FilterPinned"] = "📌 Angeheftet",
            ["QuickPaste_FilterDate"] = "📅 Datum",
            ["QuickPaste_FilterSensitive"] = "🔒 Vertraulich",
            ["QuickPaste_PinTooltip"] = "Fenster anheften (Strg+T)",
            ["QuickPaste_DockTooltip"] = "Am Bildschirmrand andocken (Strg+D)",
            ["QuickPaste_SettingsTooltip"] = "Einstellungen (Strg+,)",
            ["QuickPaste_HelpTooltip"] = "Tastenkombinationen (F1)",
            ["QuickPaste_StopStack"] = "Stapel anhalten",
            ["QuickPaste_Next"] = "Weiter (Strg+V)",
            ["QuickPaste_ItemsCount"] = "{0} Einträge",
            ["QuickPaste_EmptyTitle"] = "Verlauf ist leer",
            ["QuickPaste_EmptySubtitle"] = "Kopierte Inhalte erscheinen automatisch hier",

            ["Tray_QuickPaste"] = "Schnell-Einfügen",
            ["Tray_StopPasteStack"] = "Einfügestapel anhalten",
            ["Tray_PauseCapture"] = "Aufzeichnung anhalten",
            ["Tray_ResumeCapture"] = "Aufzeichnung fortsetzen",
            ["Tray_ClearHistory"] = "Verlauf leeren (angeheftete behalten)",
            ["Tray_StartWithWindows"] = "Mit Windows starten",
            ["Tray_OpenDataFolder"] = "Datenordner öffnen",
            ["Tray_Settings"] = "Einstellungen…",
            ["Tray_EditSettingsJson"] = "settings.json bearbeiten (erweitert)",
            ["Tray_CheckForUpdates"] = "Nach Updates suchen…",
            ["Tray_Exit"] = "Beenden",
            ["Tray_RunningTooltip"] = "Zwischenablage-Manager (aktiv)\n{0} zum Öffnen",
            ["Tray_PausedTooltip"] = "Zwischenablage-Manager (pausiert)\n{0} zum Öffnen",

            ["Dialog_ClearHistoryTitle"] = "Verlauf leeren",
            ["Dialog_ClearHistoryConfirm"] = "Gesamten Verlauf außer angehefteten Elementen löschen?",
            ["Dialog_DeleteSnippetTitle"] = "Textbaustein löschen",
            ["Dialog_DeleteSnippetConfirm"] = "Textbaustein \"{0}\" wirklich löschen?",
            ["Snippet_TitleNew"] = "Neuer Textbaustein",
            ["Snippet_TitleEdit"] = "Textbaustein bearbeiten",
            ["Snippet_Name"] = "Name",
            ["Snippet_Text"] = "Text (unterstützt {date}, {time}, {clip})",
            ["Snippet_Save"] = "Speichern",
            ["Snippet_Cancel"] = "Abbrechen"
        },

        ["ru"] = new()
        {
            ["Settings_Title"] = "Менеджер буфера обмена — Настройки",
            ["Settings_Heading"] = "Настройки",
            ["Settings_Subtitle"] = "Конфигурация системы",
            ["Settings_General_Title"] = "Общие",
            ["Settings_General_Subtitle"] = "Горячие клавиши, история и интерфейс приложения",
            ["Settings_Privacy_Title"] = "Конфиденциальность",
            ["Settings_Privacy_Subtitle"] = "Безопасность данных, шифрование и защита секретов",
            ["Settings_Retention_Title"] = "Срок хранения",
            ["Settings_Workspaces_Title"] = "Рабочие области",
            ["Settings_Snippets_Title"] = "Шаблоны",
            ["Settings_Tab_General"] = "Общие",
            ["Settings_Tab_Privacy"] = "Конфиденциальность",
            ["Settings_Tab_Retention"] = "Срок хранения",
            ["Settings_Tab_Workspaces"] = "Рабочие области",
            ["Settings_Tab_Snippets"] = "Шаблоны",

            ["Settings_Language"] = "Язык интерфейса",
            ["Settings_Language_Hint"] = "Выберите язык отображения приложения.",
            ["Settings_Hotkey"] = "Горячая клавиша быстрой вставки",
            ["Settings_Hotkey_Hint"] = "Нажмите на поле и введите комбинацию (например Ctrl+Shift+V).",
            ["Settings_CaptureHistory"] = "Записывать историю буфера обмена",
            ["Settings_KeepAtMost"] = "Хранить не более",
            ["Settings_ItemsCountHint"] = "элементов (закрепленные и шаблоны не учитываются)",
            ["Settings_Ocr"] = "Распознавать текст на изображениях (Windows OCR)",
            ["Settings_OcrNoLang"] = "Язык OCR не установлен.",
            ["Settings_OcrRecognizes"] = "Распознает {0}.",
            ["Settings_Transparency"] = "Включить эффект матового стекла в стиле iOS",
            ["Settings_Opacity"] = "Непрозрачность",
            ["Settings_TransparencyHint"] = "Эффект акрила Windows 11 + полупрозрачная карточка в стиле iOS.",

            ["Settings_DetectSensitive"] = "Обнаруживать и скрывать секреты (API-ключи, пароли)",
            ["Settings_NeverPasswords"] = "Никогда не сохранять пароли",
            ["Settings_NeverKeys"] = "Никогда не сохранять приватные ключи",
            ["Settings_ExcludedApps"] = "Не записывать копии из этих приложений",
            ["Settings_ExcludedHint"] = "Одно приложение на строку (имя процесса).",
            ["Settings_Encrypt"] = "Шифровать историю учетной записью Windows (DPAPI)",
            ["Settings_EncryptHint"] = "Текст и изображения шифруются на диске.",

            ["Settings_RetentionHint"] = "Срок хранения каждого типа в минутах. 0 = бессрочно.",
            ["Settings_Kind"] = "Тип",
            ["Settings_Minutes"] = "Минуты",


            ["Settings_SnippetsHint"] = "Шаблоны текста для быстрой вставки (type:snippet). Переменные: {0}.",
            ["Settings_NameCol"] = "Имя",
            ["Settings_TextCol"] = "Текст",
            ["Settings_NewSnippet"] = "Создать…",
            ["Settings_EditSnippet"] = "Изменить…",
            ["Settings_DeleteSnippet"] = "Удалить",
            ["Settings_Save"] = "Сохранить",
            ["Settings_Cancel"] = "Отмена",

            ["Kind_Text"] = "Текст",
            ["Kind_Code"] = "Код",
            ["Kind_Url"] = "Ссылки",
            ["Kind_Email"] = "Электронная почта",
            ["Kind_Phone"] = "Номера телефонов",
            ["Kind_Number"] = "Числа",
            ["Kind_Image"] = "Изображения",
            ["Kind_Files"] = "Файлы",
            ["Kind_Sensitive"] = "Секреты",
            ["Kind_Password"] = "Пароли",

            ["QuickPaste_Title"] = "Быстрая вставка",
            ["QuickPaste_SearchPlaceholder"] = "Поиск в буфере обмена…",
            ["QuickPaste_All"] = "Все",
            ["QuickPaste_Code"] = "Код",
            ["QuickPaste_Images"] = "Изображения",
            ["QuickPaste_Pinned"] = "Закрепленные",
            ["QuickPaste_Snippets"] = "Шаблоны",
            ["QuickPaste_RecentSearches"] = "НЕДАВНИЕ ПОИСКИ",
            ["QuickPaste_ClearRecent"] = "Очистить",
            ["QuickPaste_Filters"] = "ФИЛЬТРЫ",
            ["QuickPaste_FilterType"] = "🏷️ Тип",
            ["QuickPaste_FilterPinned"] = "📌 Закреплено",
            ["QuickPaste_FilterDate"] = "📅 Дата",
            ["QuickPaste_FilterSensitive"] = "🔒 Секретно",
            ["QuickPaste_PinTooltip"] = "Закрепить окно (Ctrl+T)",
            ["QuickPaste_DockTooltip"] = "Прикрепить к краю экрана (Ctrl+D)",
            ["QuickPaste_SettingsTooltip"] = "Настройки (Ctrl+,)",
            ["QuickPaste_HelpTooltip"] = "Горячие клавиши (F1)",
            ["QuickPaste_StopStack"] = "Остановить стек",
            ["QuickPaste_Next"] = "Далее (Ctrl+V)",
            ["QuickPaste_ItemsCount"] = "{0} элементов",
            ["QuickPaste_EmptyTitle"] = "История буфера пуста",
            ["QuickPaste_EmptySubtitle"] = "Скопированные элементы появятся здесь",

            ["Tray_QuickPaste"] = "Быстрая вставка",
            ["Tray_StopPasteStack"] = "Остановить стек вставки",
            ["Tray_PauseCapture"] = "Приостановить запись",
            ["Tray_ResumeCapture"] = "Возобновить запись",
            ["Tray_ClearHistory"] = "Очистить историю (кроме закрепленных)",
            ["Tray_StartWithWindows"] = "Запуск при старте Windows",
            ["Tray_OpenDataFolder"] = "Открыть папку данных",
            ["Tray_Settings"] = "Настройки…",
            ["Tray_EditSettingsJson"] = "Редактировать settings.json (дополнительно)",
            ["Tray_CheckForUpdates"] = "Проверить обновления…",
            ["Tray_Exit"] = "Выход",
            ["Tray_RunningTooltip"] = "Менеджер буфера обмена (запись)\n{0} для открытия",
            ["Tray_PausedTooltip"] = "Менеджер буфера обмена (пауза)\n{0} для открытия",

            ["Dialog_ClearHistoryTitle"] = "Очистить историю",
            ["Dialog_ClearHistoryConfirm"] = "Удалить всю историю, кроме закрепленных элементов?",
            ["Dialog_DeleteSnippetTitle"] = "Удалить шаблон",
            ["Dialog_DeleteSnippetConfirm"] = "Удалить шаблон \"{0}\"?",
            ["Snippet_TitleNew"] = "Новый шаблон",
            ["Snippet_TitleEdit"] = "Редактировать шаблон",
            ["Snippet_Name"] = "Имя",
            ["Snippet_Text"] = "Текст (поддерживает {date}, {time}, {clip})",
            ["Snippet_Save"] = "Сохранить",
            ["Snippet_Cancel"] = "Отмена"
        },

        ["pt"] = new()
        {
            ["Settings_Title"] = "Gerenciador de Área de Transferência — Configurações",
            ["Settings_Heading"] = "Configurações",
            ["Settings_Subtitle"] = "Configuração do sistema",
            ["Settings_General_Title"] = "Geral",
            ["Settings_General_Subtitle"] = "Atalhos de teclado, histórico e interface do aplicativo",
            ["Settings_Privacy_Title"] = "Privacidade",
            ["Settings_Privacy_Subtitle"] = "Segurança de dados, criptografia e proteção de informações confidenciais",
            ["Settings_Retention_Title"] = "Retenção",
            ["Settings_Workspaces_Title"] = "Espaços de trabalho",
            ["Settings_Snippets_Title"] = "Modelos",
            ["Settings_Tab_General"] = "Geral",
            ["Settings_Tab_Privacy"] = "Privacidade",
            ["Settings_Tab_Retention"] = "Retenção",
            ["Settings_Tab_Workspaces"] = "Espaços de trabalho",
            ["Settings_Tab_Snippets"] = "Modelos",

            ["Settings_Language"] = "Idioma",
            ["Settings_Language_Hint"] = "Idioma de exibição do aplicativo.",
            ["Settings_Hotkey"] = "Atalho Colagem Rápida",
            ["Settings_Hotkey_Hint"] = "Clique no campo e pressione o atalho desejado (ex: Ctrl+Shift+V).",
            ["Settings_CaptureHistory"] = "Gravar histórico da área de transferência",
            ["Settings_KeepAtMost"] = "Manter no máximo",
            ["Settings_ItemsCountHint"] = "itens (itens fixados e modelos não contam)",
            ["Settings_Ocr"] = "Reconhecer texto em imagens (Windows OCR, offline)",
            ["Settings_OcrNoLang"] = "Nenhum idioma de OCR instalado.",
            ["Settings_OcrRecognizes"] = "Reconhece {0}.",
            ["Settings_Transparency"] = "Habilitar transparência estilo vidro fosco do iOS",
            ["Settings_Opacity"] = "Opacidade",
            ["Settings_TransparencyHint"] = "Efeito acrílico do Windows 11 + cartão translúcido estilo iOS moderno.",

            ["Settings_DetectSensitive"] = "Detectar e ocultar dados confidenciais (chaves de API, tokens, senhas)",
            ["Settings_NeverPasswords"] = "Nunca salvar senhas",
            ["Settings_NeverKeys"] = "Nunca salvar chaves privadas",
            ["Settings_ExcludedApps"] = "Não gravar cópias destes aplicativos",
            ["Settings_ExcludedHint"] = "Um aplicativo por linha (nome do processo, ex: KeePass).",
            ["Settings_Encrypt"] = "Criptografar histórico com a conta Windows (DPAPI)",
            ["Settings_EncryptHint"] = "Textos e imagens são criptografados no disco.",

            ["Settings_RetentionHint"] = "Tempo de retenção em minutos. 0 = até ser excluído.",
            ["Settings_Kind"] = "Tipo",
            ["Settings_Minutes"] = "Minutos",


            ["Settings_SnippetsHint"] = "Modelos de texto reutilizáveis (type:snippet). Variáveis: {0}.",
            ["Settings_NameCol"] = "Nome",
            ["Settings_TextCol"] = "Texto",
            ["Settings_NewSnippet"] = "Novo…",
            ["Settings_EditSnippet"] = "Editar…",
            ["Settings_DeleteSnippet"] = "Excluir",
            ["Settings_Save"] = "Salvar",
            ["Settings_Cancel"] = "Cancelar",

            ["Kind_Text"] = "Texto",
            ["Kind_Code"] = "Código",
            ["Kind_Url"] = "Links",
            ["Kind_Email"] = "E-mails",
            ["Kind_Phone"] = "Telefones",
            ["Kind_Number"] = "Números",
            ["Kind_Image"] = "Imagens",
            ["Kind_Files"] = "Arquivos",
            ["Kind_Sensitive"] = "Confidencial",
            ["Kind_Password"] = "Senhas",

            ["QuickPaste_Title"] = "Colagem Rápida",
            ["QuickPaste_SearchPlaceholder"] = "Pesquisar área de transferência…",
            ["QuickPaste_All"] = "Tudo",
            ["QuickPaste_Code"] = "Código",
            ["QuickPaste_Images"] = "Imagens",
            ["QuickPaste_Pinned"] = "Fixados",
            ["QuickPaste_Snippets"] = "Modelos",
            ["QuickPaste_RecentSearches"] = "BUSCAS RECENTES",
            ["QuickPaste_ClearRecent"] = "Limpar",
            ["QuickPaste_Filters"] = "FILTROS",
            ["QuickPaste_FilterType"] = "🏷️ Tipo",
            ["QuickPaste_FilterPinned"] = "📌 Fixado",
            ["QuickPaste_FilterDate"] = "📅 Data",
            ["QuickPaste_FilterSensitive"] = "🔒 Confidencial",
            ["QuickPaste_PinTooltip"] = "Fixar janela (Ctrl+T)",
            ["QuickPaste_DockTooltip"] = "Encaixar na borda da tela (Ctrl+D)",
            ["QuickPaste_SettingsTooltip"] = "Configurações (Ctrl+,)",
            ["QuickPaste_HelpTooltip"] = "Atalhos de teclado (F1)",
            ["QuickPaste_StopStack"] = "Parar pilha",
            ["QuickPaste_Next"] = "Próximo (Ctrl+V)",
            ["QuickPaste_ItemsCount"] = "{0} itens",
            ["QuickPaste_EmptyTitle"] = "O histórico está vazio",
            ["QuickPaste_EmptySubtitle"] = "Itens copiados aparecerão aqui automaticamente",

            ["Tray_QuickPaste"] = "Colagem Rápida",
            ["Tray_StopPasteStack"] = "Parar pilha de colagem",
            ["Tray_PauseCapture"] = "Pausar captura",
            ["Tray_ResumeCapture"] = "Retomar captura",
            ["Tray_ClearHistory"] = "Limpar histórico (mantém fixados)",
            ["Tray_StartWithWindows"] = "Iniciar com o Windows",
            ["Tray_OpenDataFolder"] = "Abrir pasta de dados",
            ["Tray_Settings"] = "Configurações…",
            ["Tray_EditSettingsJson"] = "Editar settings.json (avançado)",
            ["Tray_CheckForUpdates"] = "Verificar atualizações…",
            ["Tray_Exit"] = "Sair",
            ["Tray_RunningTooltip"] = "Gerenciador de Área de Transferência (gravando)\n{0} para abrir",
            ["Tray_PausedTooltip"] = "Gerenciador de Área de Transferência (pausado)\n{0} para abrir",

            ["Dialog_ClearHistoryTitle"] = "Limpar histórico",
            ["Dialog_ClearHistoryConfirm"] = "Excluir todo o histórico exceto itens fixados?",
            ["Dialog_DeleteSnippetTitle"] = "Excluir modelo",
            ["Dialog_DeleteSnippetConfirm"] = "Excluir o modelo \"{0}\"?",
            ["Snippet_TitleNew"] = "Novo modelo",
            ["Snippet_TitleEdit"] = "Editar modelo",
            ["Snippet_Name"] = "Nome",
            ["Snippet_Text"] = "Texto (suporta {date}, {time}, {clip})",
            ["Snippet_Save"] = "Salvar",
            ["Snippet_Cancel"] = "Cancelar"
        }
    };
}
